projects:
  sparkLite:
    schema: 'http://localhost:3333/api/graphql'
    documents: 'apps/client/lite/**/*.graphql'
    extensions:
      languageService:
        useSchemaFileDefinitions: true
      codegen:
        watch: true
        generates:
          apps/test-next/generated/gql.tsx:
            plugins:
              - typescript
              - typescript-operations
              - typescript-react-apollo

  spark:
    schema: 'http://localhost:3334/api/graphql'
    documents: 'apps/client/spark/**/*.graphql'
    extensions:
      languageService:
        useSchemaFileDefinitions: true
      codegen:
        watch: true
        generates:
          apps/some-client/generated/gql.tsx:
            plugins:
              - typescript
              - typescript-operations
              - typescript-react-apollo





