projects:
  spark-log:
    schema:
      # SERVER SIDE
      #- 'http://localhost:5100/api/graphql'
      # FILE
      - 'libs/gql/log-app/src/schema/schema.gql'
    documents: 'libs/gql/log-app/src/queries/**/*.graphql'
    extensions:
      languageService:
        useSchemaFileDefinitions: true
      codegen:
        watch: true
        generates:
          libs/gql/log-app/src/types/gql.tsx:
            plugins:
              - typescript
              - typescript-operations
              - typescript-react-apollo
