module.exports = {
  projects: [
    '<rootDir>/apps/client/lite',
    '<rootDir>/apps/api/lite-srv',
    '<rootDir>/apps/mobile/spark',
    '<rootDir>/libs/styles/theme',
    '<rootDir>/libs/client-lib/apollo-next',
    '<rootDir>/libs/storybook/lite',
    '<rootDir>/libs/shared/assets',
    '<rootDir>/apps/mobile/demo-7',
    '<rootDir>/libs/service-lib/agora',
    '<rootDir>/libs/service-lib/lemma',
    '<rootDir>/libs/service-lib/translator',
    '<rootDir>/libs/storybook/seven',
    '<rootDir>/libs/ui/web/atom',
    '<rootDir>/libs/ui/web/card',
    '<rootDir>/libs/ui/web/navs',
    '<rootDir>/libs/ui/web/chat',
    '<rootDir>/libs/ui/web/carousel',
    '<rootDir>/libs/hooks/auth',
    '<rootDir>/libs/hook/chat',
    '<rootDir>/libs/hook/voice',
    '<rootDir>/libs/hook/recog',
    '<rootDir>/libs/client-lib/agora',
    '<rootDir>/libs/hook/store',
    '<rootDir>/libs/client-lib/firebase',
  ],
};
