name: Firebase Hosting Deployment
on:
  push:
    branches:
      - dev
      - master
    paths:
      - 'firebase.json'
      - '.firebaserc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # OUTPUT WHICH BRANCH HAS BEEN CHANGED
      - name: Output the branch name!
        id: pushed_branch
        run: echo ::set-output name=name::$(echo $GITHUB_REF | cut -d'/' -f 3)
      # Changed Branch Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ steps.pushed_branch.outputs.name }}

      - name: Firebase Hosting Change Deployment
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GC_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: hessed
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
